baseurl = "/"
languageCode = "en-us"
title = "Strata"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Judy Hong"
	description = "Personal site for data science projects and thoughts."

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Judy**, a small city girl with big dreams.<br> Aspiring data scientist,<br>
		reader on planes and trains."
		
		# The icons will be shown if you enter your username
		twitter = ""
		github = "judyh97"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Judy Hong",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = true
		title = "Ipsum lorem dolor aliquam ante commodo magna sed accumsan arcu neque."
		content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."

	[params.portfolio]
		hide  = false
		title = "Recent Places"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "Penn.jpg"
			thumb = "Penn.jpg"
			title = "University of Pennsylvania"
			description = "Class of 2020 | College of Arts and Sciences | Wharton School"

		[[params.portfolio.gallery]]
			image = "Singapore.jpg"
			thumb = "Singapore.jpg"
			title = "Home"
			description = "Singapore"
			
		[[params.portfolio.gallery]]
			image = "Cape.jpg"
			thumb = "Cape.jpg"
			title = "Cape Town, South Africa"
			description = "iXperience | Data Science"
			
		[[params.portfolio.gallery]]
			image = "Srilanka.jpg"
			thumb = "Srilanka.jpg"
			title = "Sri Lanka"
			description = "the friends you'll never have again"

		[[params.portfolio.gallery]]
			image = "London.jpg"
			thumb = "London.jpg"
			title = "London"
			description = "is a riddle"

		[[params.portfolio.gallery]]
			image = "Paris.jpg"
			thumb = "Paris.jpg"
			title = "Paris"
			description = "is an explanation"
			
	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = ""

    address = [
		]
		phone = ""

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "judy.rl.hong@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Projects"
	url  = "categories/Projects"
	weight = 10
	
[[menu.main]]
	name = "Thoughts"
	url  = "categories/Thoughts"
	weight = 10
	