---
title: 'Police: Yay or Nay?'
author: ~
date: '2017-07-18'
slug: police-yay-or-nay
categories: ["Projects"]
tags: []
---



<p>Fans of anime will be familiar with Gen Urobuchi’s <em>Psycho-Pass</em>. In an authoritarian future dystopia, aggregated personality data and background information are used to gauge the probability of a citizen committing a crime. With the help of omnipresent public sensors that continuously scan the mental states of every passing citizen, authorities are alerted whenever excessive crime probability ratings are detected, whereafter officers are dispatched to make premature arrests. This concept can also be found in <em>Minority Report</em> (which i watched on the plane to Cape Town).</p>
<p>A future in which we can accurately predict outcomes in crime and victimization — is that possible? With machine learning, perhaps very much so. Here, I take a stab at it.</p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>I’ll be using the National Crime Victimization Survey (NCVS), which is administered by the Bureau of Justice Statistics in the United States. This survey collects criminal victimization data annually from a representative sample of about 160,000 persons interviewed each year. The <a href="https://www.bjs.gov/index.cfm?ty=dcdetail&amp;iid=245">NCVS</a> provides the largest national forum for victims to describe the impact of crime and characteristics of violent offenders.</p>
<p>One key finding of the survey was that many crimes went unreported. Why is that so, and what factors surrounding the crime make it more likely for the victim to not make a police report? By analyzing both the characteristics and consequences of criminal victimization cases from 1995-2015, I seek to answer this question.</p>
</div>
<div id="the-data" class="section level1">
<h1>The Data</h1>
<p>Data is from the <a href="https://www.bjs.gov/developer/ncvs/index.cfm">Personal Victimization dataset</a> for 1993-2015. The cleaned dataset has 23684 datapoints spanning 12 years.</p>
<p>Let’s take a look at the variables being analyzed:</p>
<pre><code>##  [1] &quot;year&quot;      &quot;gender&quot;    &quot;race1r&quot;    &quot;hispanic&quot;  &quot;ethnic1r&quot; 
##  [6] &quot;ager&quot;      &quot;marital2&quot;  &quot;hincome&quot;   &quot;popsize&quot;   &quot;region&quot;   
## [11] &quot;msa&quot;       &quot;direl&quot;     &quot;weapon&quot;    &quot;weapcat&quot;   &quot;newcrime&quot; 
## [16] &quot;newoff&quot;    &quot;injury&quot;    &quot;treatment&quot; &quot;locationr&quot; &quot;notify&quot;</code></pre>
<p>Our initial list of explanatory variables, all categorical except for year: | Variable | Explanation | | ——– | :———: | | year | Year of data collection | | gender | Gender of respondent | | race1r | Race of respondent | | hispanic | Hispanic origin | | ethnic1r | Race/Hispanic origin | | ager | Age of respondent | | marital2 | Marital Status | | hincome | Household Income | | popsize | Population size of crime location | | region | Region of crime location | | msa | Urban, Suburban, Rural | | direl | Victim-offender Relationship | | weapon | Weapon Use | | weapcat | Weapon Type | | newcrime | Aggregate Type of crime, i.e. Violent Victimization/ Theft | | newoff | Type of crime | | injury | Injured/ Not injured | | treatment | Medical Treatment for injuries | | locationr | Location of Incident, i.e School, Public, Home… |</p>
<p>The dependent variable we’re analyzing is <strong>notify</strong>: whether the crime was reported to the police or not.</p>
</div>
<div id="explanatory-analysis" class="section level1">
<h1>Explanatory Analysis</h1>
<p>I begin by plotting each explanatory variable as a function of <strong>notify</strong>.</p>
<p><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-1.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-2.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-3.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-4.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-5.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-6.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-7.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-8.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-9.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-10.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-11.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-12.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-13.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-14.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-15.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-16.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-17.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-18.png" width="672" /><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-2-19.png" width="672" /></p>
<p>It appears that all the explanatory variables have some influence on <strong>notify</strong> except for <strong>popsize</strong>, <strong>newcrime</strong> and <strong>year</strong>. These variables will be excluded from all subsequent analyses.</p>
</div>
<div id="hypothesis" class="section level1">
<h1>Hypothesis</h1>
<p>I hypothesize that severity of crime may be correlated to whether it is reported; severity is indicated by <strong>weapon</strong>, <strong>weapcat</strong>, <strong>newoff</strong>, <strong>injury</strong> and <strong>treatment</strong>. For example, we see above that crimes involving weapons, especially firearms, are more likely to be reported.</p>
<p>For circumstances of crime, initial observations are counterintuitive: crimes in homes are more likely to be reported, and intimates are more likely to be reported than acquaintances.</p>
<p>Characteristics of the victim, such as age, marital status, household income and gender seems to have some effect as well.</p>
</div>
<div id="experiment-analysis" class="section level1">
<h1>Experiment/ Analysis</h1>
<p>I begin by splitting the data 80:20 into training and testing sets; the training set will be used to train the model, while the testing set will be used to assess the model accuracy.</p>
<pre class="r"><code>index = sample(1:nrow(data.clean), round(0.8 *nrow(data.clean)))
data.train = data.clean[index, ]
data.test = data.clean[-index, ]</code></pre>
<div id="logistic-regression" class="section level2">
<h2>Logistic Regression</h2>
<p>Using the chosen explanatory variables, I first fit a logistic regression.</p>
<pre class="r"><code>totest = &quot;gender + race1r + ager + marital2 + hincome + region + msa + direl + weapon + weapcat + newoff + injury + treatment + locationr&quot;
names.totest = as.formula(paste(&quot;notify ~&quot;, totest))
fit = glm(names.totest, data = data.train, family = binomial)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## glm(formula = names.totest, family = binomial, data = data.train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3303  -1.0819   0.5588   1.0285   2.3462  
## 
## Coefficients: (2 not defined because of singularities)
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)         1.681846   0.160513  10.478  &lt; 2e-16 ***
## genderFemale       -0.244093   0.034467  -7.082 1.42e-12 ***
## race1rBlack        -0.155207   0.050206  -3.091  0.00199 ** 
## race1rOther         0.213451   0.071863   2.970  0.00298 ** 
## ager15-17          -0.418004   0.073751  -5.668 1.45e-08 ***
## ager18-20          -0.419685   0.077751  -5.398 6.75e-08 ***
## ager21-24          -0.553356   0.078080  -7.087 1.37e-12 ***
## ager25-34          -0.811630   0.073532 -11.038  &lt; 2e-16 ***
## ager35-49          -0.731066   0.075850  -9.638  &lt; 2e-16 ***
## ager50-64          -0.646124   0.084493  -7.647 2.06e-14 ***
## ager&gt;65            -0.566580   0.124971  -4.534 5.80e-06 ***
## marital2Married    -0.329264   0.049152  -6.699 2.10e-11 ***
## marital2Widowed    -0.340034   0.128091  -2.655  0.00794 ** 
## marital2Divorced   -0.179173   0.057941  -3.092  0.00199 ** 
## marital2Separated   0.105011   0.074931   1.401  0.16108    
## marital288         -0.604095   0.301250  -2.005  0.04493 *  
## hincome7500-14999  -0.061207   0.064228  -0.953  0.34061    
## hincome15000-24999  0.134294   0.062912   2.135  0.03279 *  
## hincome25000-34999  0.001899   0.065167   0.029  0.97675    
## hincome35000-49999 -0.023227   0.064174  -0.362  0.71740    
## hincome50000-74999  0.062432   0.066031   0.945  0.34441    
## hincome&gt;75000       0.127329   0.066416   1.917  0.05522 .  
## regionMidwest      -0.054561   0.051488  -1.060  0.28929    
## regionSouth        -0.093881   0.049452  -1.898  0.05764 .  
## regionWest          0.043324   0.050901   0.851  0.39468    
## msaSuburban        -0.100502   0.035318  -2.846  0.00443 ** 
## msaRural           -0.146621   0.051638  -2.839  0.00452 ** 
## direlRelative      -0.006112   0.072953  -0.084  0.93324    
## direlAcquain       -0.046835   0.055944  -0.837  0.40250    
## direlStranger      -0.318311   0.058582  -5.434 5.52e-08 ***
## weaponN             0.131589   0.094475   1.393  0.16367    
## weapcatFirearm     -0.668823   0.079689  -8.393  &lt; 2e-16 ***
## weapcatKnife       -0.068536   0.080300  -0.854  0.39338    
## weapcatOther              NA         NA      NA       NA    
## newoffRob          -1.075517   0.097327 -11.051  &lt; 2e-16 ***
## newoffAssault1     -1.023701   0.109611  -9.339  &lt; 2e-16 ***
## newoffAssault2     -0.770786   0.080947  -9.522  &lt; 2e-16 ***
## newoffTheft        -0.980545   0.150011  -6.536 6.30e-11 ***
## injuryY            -1.287219   0.054942 -23.429  &lt; 2e-16 ***
## treatmentY          0.894670   0.063915  13.998  &lt; 2e-16 ***
## treatmentSelf             NA         NA      NA       NA    
## locationrNear       0.492533   0.056302   8.748  &lt; 2e-16 ***
## locationrPublic     0.637307   0.041678  15.291  &lt; 2e-16 ***
## locationrSchool     1.118915   0.063789  17.541  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 26201  on 18946  degrees of freedom
## Residual deviance: 23410  on 18905  degrees of freedom
## AIC: 23494
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Not all the factors are relevant to this model, so I fit a more parisimonious model using stepwise regression:</p>
<pre class="r"><code>fit.red = stepAIC(fit, direction = &quot;both&quot;)</code></pre>
<pre><code>## Start:  AIC=23493.79
## notify ~ gender + race1r + ager + marital2 + hincome + region + 
##     msa + direl + weapon + weapcat + newoff + injury + treatment + 
##     locationr
## 
## 
## Step:  AIC=23493.79
## notify ~ gender + race1r + ager + marital2 + hincome + region + 
##     msa + direl + weapon + weapcat + newoff + treatment + locationr
## 
## 
## Step:  AIC=23493.79
## notify ~ gender + race1r + ager + marital2 + hincome + region + 
##     msa + direl + weapcat + newoff + treatment + locationr
## 
##             Df Deviance   AIC
## &lt;none&gt;            23410 23494
## - region     3    23422 23500
## - msa        2    23421 23501
## - hincome    6    23430 23502
## - race1r     2    23430 23510
## - gender     1    23460 23542
## - direl      3    23469 23547
## - marital2   5    23475 23549
## - weapcat    3    23523 23601
## - ager       7    23545 23615
## - newoff     4    23545 23621
## - locationr  3    23818 23896
## - treatment  2    24028 24108</code></pre>
<pre class="r"><code>summary(fit.red)</code></pre>
<pre><code>## 
## Call:
## glm(formula = notify ~ gender + race1r + ager + marital2 + hincome + 
##     region + msa + direl + weapcat + newoff + treatment + locationr, 
##     family = binomial, data = data.train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3303  -1.0819   0.5588   1.0285   2.3462  
## 
## Coefficients:
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)         1.813434   0.133047  13.630  &lt; 2e-16 ***
## genderFemale       -0.244093   0.034467  -7.082 1.42e-12 ***
## race1rBlack        -0.155207   0.050206  -3.091  0.00199 ** 
## race1rOther         0.213451   0.071863   2.970  0.00298 ** 
## ager15-17          -0.418004   0.073751  -5.668 1.45e-08 ***
## ager18-20          -0.419685   0.077751  -5.398 6.75e-08 ***
## ager21-24          -0.553356   0.078080  -7.087 1.37e-12 ***
## ager25-34          -0.811630   0.073532 -11.038  &lt; 2e-16 ***
## ager35-49          -0.731066   0.075850  -9.638  &lt; 2e-16 ***
## ager50-64          -0.646124   0.084493  -7.647 2.06e-14 ***
## ager&gt;65            -0.566580   0.124971  -4.534 5.80e-06 ***
## marital2Married    -0.329264   0.049152  -6.699 2.10e-11 ***
## marital2Widowed    -0.340034   0.128091  -2.655  0.00794 ** 
## marital2Divorced   -0.179173   0.057941  -3.092  0.00199 ** 
## marital2Separated   0.105011   0.074931   1.401  0.16108    
## marital288         -0.604095   0.301250  -2.005  0.04493 *  
## hincome7500-14999  -0.061207   0.064228  -0.953  0.34061    
## hincome15000-24999  0.134294   0.062912   2.135  0.03279 *  
## hincome25000-34999  0.001899   0.065167   0.029  0.97675    
## hincome35000-49999 -0.023227   0.064174  -0.362  0.71740    
## hincome50000-74999  0.062432   0.066031   0.945  0.34441    
## hincome&gt;75000       0.127329   0.066416   1.917  0.05522 .  
## regionMidwest      -0.054561   0.051488  -1.060  0.28929    
## regionSouth        -0.093881   0.049452  -1.898  0.05764 .  
## regionWest          0.043324   0.050901   0.851  0.39468    
## msaSuburban        -0.100502   0.035318  -2.846  0.00443 ** 
## msaRural           -0.146621   0.051638  -2.839  0.00452 ** 
## direlRelative      -0.006112   0.072953  -0.084  0.93324    
## direlAcquain       -0.046835   0.055944  -0.837  0.40250    
## direlStranger      -0.318311   0.058582  -5.434 5.52e-08 ***
## weapcatFirearm     -0.800412   0.090762  -8.819  &lt; 2e-16 ***
## weapcatKnife       -0.200125   0.094535  -2.117  0.03426 *  
## weapcatOther       -0.131589   0.094475  -1.393  0.16367    
## newoffRob          -1.075517   0.097327 -11.051  &lt; 2e-16 ***
## newoffAssault1     -1.023701   0.109611  -9.339  &lt; 2e-16 ***
## newoffAssault2     -0.770786   0.080947  -9.522  &lt; 2e-16 ***
## newoffTheft        -0.980545   0.150011  -6.536 6.30e-11 ***
## treatmentY         -0.392549   0.044601  -8.801  &lt; 2e-16 ***
## treatmentSelf      -1.287219   0.054942 -23.429  &lt; 2e-16 ***
## locationrNear       0.492533   0.056302   8.748  &lt; 2e-16 ***
## locationrPublic     0.637307   0.041678  15.291  &lt; 2e-16 ***
## locationrSchool     1.118915   0.063789  17.541  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 26201  on 18946  degrees of freedom
## Residual deviance: 23410  on 18905  degrees of freedom
## AIC: 23494
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Assessing model accuracy:</p>
<pre class="r"><code>test.prediction = predict(fit.red, newdata = data.test)
test.class = ifelse(test.prediction &gt; 0.5, &quot;N&quot;, &quot;Y&quot;)
table(test.class, data.test$notify) #read: horizontal label is truth, vertical label predicted</code></pre>
<pre><code>##           
## test.class    Y    N
##          N  390 1090
##          Y 1894 1363</code></pre>
<pre class="r"><code>(Accuracy = (1842 + 1113) / (1842 + 1113 + 376 + 1406))</code></pre>
<pre><code>## [1] 0.6238125</code></pre>
<p>We see that the accuracy of this model is 0.6238125. In the final model, all explanatory variables were included except <strong>injury</strong> and <strong>weapon</strong>.</p>
<p>Can we improve on this accuracy by using a decision tree?</p>
</div>
<div id="decision-tree" class="section level2">
<h2>Decision Tree</h2>
<pre class="r"><code>(fit.tree = train(names.totest, data = data.clean, method = &quot;rpart&quot;, trControl = trainControl(method = &quot;repeatedcv&quot;, repeats = 3)))</code></pre>
<pre><code>## CART 
## 
## 23684 samples
##    14 predictor
##     2 classes: &#39;Y&#39;, &#39;N&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold, repeated 3 times) 
## Summary of sample sizes: 21315, 21316, 21316, 21316, 21315, 21315, ... 
## Resampling results across tuning parameters:
## 
##   cp           Accuracy   Kappa     
##   0.002678093  0.6419527  0.27790589
##   0.030842707  0.6165770  0.21756106
##   0.056299470  0.5582651  0.07344444
## 
## Accuracy was used to select the optimal model using  the largest value.
## The final value used for the model was cp = 0.002678093.</code></pre>
<p>Using cross-validation, we see that an good complexity level to use in fitting a decision tree is cp = 0.002678093. I refit the decision tree:</p>
<pre class="r"><code>fit.tree.2 = rpart(names.totest, data = data.train, control = rpart.control(cp = 0.002678093198))
fancyRpartPlot(fit.tree.2)</code></pre>
<p><img src="/post/2017-07-18-police-yay-or-nay_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Assessing accuracy:</p>
<pre class="r"><code>prediction.2 = predict(fit.tree.2, data.test)
test.class.2 = ifelse(prediction.2[, 1] &gt; 0.5, &quot;Y&quot;, &quot;N&quot;)
table(test.class.2, data.test$notify)</code></pre>
<pre><code>##             
## test.class.2    Y    N
##            N  917 1710
##            Y 1367  743</code></pre>
<pre class="r"><code>(Accuracy.2 = (1328 + 1751) / (1328 + 1751 + 890 + 768))</code></pre>
<pre><code>## [1] 0.6499894</code></pre>
<p>The decision tree performs only marginally better than logistic regression, with accuracy at 0.6499894. Not much meaningful information can be drawn from the way outcomes split.</p>
</div>
</div>
<div id="conclusions" class="section level1">
<h1>Conclusions</h1>
<p>Both the logistic regression and decision tree models do not perform well at predicting whether a victim will notify the police. However, seeing that explanatory variables may be highly interrelated, I could try feature engineering (e.g. relating <strong>marital2</strong> with <strong>gender</strong>, <strong>weapon</strong> with <strong>weapcat</strong>) or other machine learning algorithms such as neural networks.</p>
<p><strong>SPOILER ALERT</strong></p>
<p>In the last episode of <em>Psycho-Pass</em>, it is revealed that the crime coefficients are calculated by a hive mind made up of hundreds of brains… sounds awfully like neural networks to me!</p>
<div class="figure">
<img src="Sibyl_System.png" alt="Sibyl System" />
<p class="caption">Sibyl System</p>
</div>
</div>
